# Generated by Django 4.1.3 on 2022-12-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('headline', models.TextField()),
                ('reportedAt', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'news',
            },
        ),
    ]
