# Generated by Django 4.1.2 on 2022-11-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='description_table',
            fields=[
                ('desc_id', models.TextField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('pos', models.IntegerField()),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pos_overall', models.IntegerField(blank=True, null=True)),
                ('url_shown', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='domain_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='frequency_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='keyword_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(null=True)),
                ('req_url', models.TextField(blank=True, null=True)),
                ('with_year', models.BooleanField(null=True)),
                ('search_volume', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rel_search_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_search', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tag_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sitelink_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_type', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.description_table')),
            ],
        ),
        migrations.CreateModel(
            name='rel_question_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_question', models.TextField(null=True)),
                ('pos', models.IntegerField(null=True)),
                ('answer', models.TextField(null=True)),
                ('source_url', models.TextField(null=True)),
                ('source_title', models.TextField(null=True)),
                ('url_shown', models.TextField(null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.domain_table')),
            ],
        ),
        migrations.CreateModel(
            name='question_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('pos', models.IntegerField()),
                ('desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.description_table')),
            ],
        ),
        migrations.CreateModel(
            name='keyword_tag_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.keyword_table')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.tag_table')),
            ],
        ),
        migrations.CreateModel(
            name='keyword_rel_search_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.keyword_table')),
                ('rel_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.rel_search_table')),
            ],
        ),
        migrations.CreateModel(
            name='keyword_rel_question_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.keyword_table')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.rel_question_table')),
            ],
        ),
        migrations.CreateModel(
            name='keyword_frequency_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.frequency_table')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.keyword_table')),
            ],
        ),
        migrations.CreateModel(
            name='keyword_brand_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.brand_table')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.keyword_table')),
            ],
        ),
        migrations.AddField(
            model_name='description_table',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.domain_table'),
        ),
        migrations.AddField(
            model_name='description_table',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.keyword_table'),
        ),
    ]
