# Generated by Django 4.1.2 on 2022-11-10 12:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import rank_tool.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('file_name', models.CharField(max_length=252)),
                ('file', models.FileField(upload_to=rank_tool.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('status', models.CharField(choices=[('In Queue', 'In Queue'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Email Sent', 'Email Sent')], default='In Queue', max_length=15)),
                ('time_created', models.DateTimeField()),
                ('time_complete', models.DateTimeField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('current', models.IntegerField(null=True)),
                ('result', models.FileField(null=True, upload_to='')),
                ('result_mod', models.FileField(null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=models.SET(rank_tool.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
