# Generated by Django 3.2.8 on 2021-11-16 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=400)),
                ('tag', models.CharField(max_length=200)),
                ('search_volume', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=200)),
                ('exam_tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('domain', models.CharField(max_length=600)),
                ('url', models.TextField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.keywords')),
            ],
        ),
    ]
