# Generated by Django 3.2.8 on 2021-11-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleserp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
